name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    uses: ./.github/workflows/node-check.yml
    with:
      run-script: typecheck

  lint:
    uses: ./.github/workflows/node-check.yml
    with:
      run-script: lint

  test:
    uses: ./.github/workflows/node-check.yml
    with:
      run-script: test
